--- #YAML:1.0
name:                XML-Sig
version:             0.22
abstract:            An XML Digital Signature Toolkit
license:             perl
author:              
    - Byrne Reese <byrne@majordojo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor:               0
    Crypt::OpenSSL::DSA:           0
    Crypt::OpenSSL::RSA:           0
    Crypt::OpenSSL::X509:          0
    Digest::SHA1:                  0
    File::Which:                   0
    MIME::Base64:                  0
    Test::Exception:               0
    XML::CanonicalizeXML:          0
    XML::XPath:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
